const CACHE_KEY_GET_SIGNUP_USER = 'GET_SIGNUP_USER';
const CACHE_KEY_USER_INFORMATION = 'CACHE_KEY_USER_INFORMATION';

const CACHE_KEY_FETCH_CREDITS = 'CACHE_KEY_FETCH_CREDITS';
const CACHE_KEY_FETCH_CREDIT = 'CACHE_KEY_FETCH_CREDIT';

const CACHE_KEY_FETCH_STUDENTS = 'CACHE_KEY_FETCH_STUDENTS';
const CACHE_KEY_CREDIT_OWNERS = 'CACHE_KEY_CREDIT_OWNERS';

const CREDIT_ADMINS = 'CREDIT_ADMINS';
const CACHE_KEY_FETCH_CREDIT_ADMINS = [CREDIT_ADMINS];

const CACHE_KEY_FETCH_PROJECTS = 'CACHE_KEY_FETCH_PROJECTS';

export {
	CACHE_KEY_CREDIT_OWNERS,
	CACHE_KEY_FETCH_CREDIT,
	CACHE_KEY_FETCH_CREDIT_ADMINS,
	CACHE_KEY_FETCH_CREDITS,
	CACHE_KEY_FETCH_PROJECTS,
	CACHE_KEY_FETCH_STUDENTS,
	CACHE_KEY_GET_SIGNUP_USER,
	CACHE_KEY_USER_INFORMATION,
	CREDIT_ADMINS,
};
