const CACHE_KEY_GET_SIGNUP_USER = 'GET_SIGNUP_USER';
const CACHE_KEY_USER_INFORMATION = 'CACHE_KEY_USER_INFORMATION';

const CACHE_KEY_FETCH_CREDITS = 'CACHE_KEY_FETCH_CREDITS';

export { CACHE_KEY_FETCH_CREDITS, CACHE_KEY_GET_SIGNUP_USER, CACHE_KEY_USER_INFORMATION };
